name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
  
    - name: Compile with javac
      run: javac src/Main.java -d out

    - name: Run Java application
      run: java -cp out Main

    - name: Mensagem de Sucesso
      run: echo Deu Green
      
    - name: Docker Build & Push Action
  # You may pin to the exact commit or the version.
  # uses: mr-smithers-excellent/docker-build-push@59523c638baec979a74fea99caa9e29d97e5963c
      uses: mr-smithers-excellent/docker-build-push@v6.4
      with:
        # Name of the Docker image
        image: artursousa/pipenativo
        tags: ${{ github.run_number }}
        registry: docker.io
        dockerfile: dockerfile
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        # Tags override for Docker image
       
   
          
